CC = gcc
CFLAGS = -I. -fPIC -fomit-frame-pointer -m32
LD = gcc
LDFLAGS = -L. -shared -m32
NAME = libmsgctl-i586.so
OBJS = msgctl.o
LIBS =

all:	$(NAME)
	echo done

clean:
	rm *.o *.so*

$(NAME):	$(OBJS)
	$(LD) $(LDFLAGS) $(OBJS) $(LIBS) -o $(NAME)

%.o:%.c msgctl.h
	$(CC) -c $(CFLAGS) $+
